"""AI employee automation, credentials, telephony and generic action evidence.

Frozen schema; upgrading preserves existing action/attempt/receipt rows.
SQLite batch recreation requires foreign_keys OFF before the transaction.
Refuse an unsafe SQLite invocation rather than cascading deletes of evidence.
"""

from alembic import op
import sqlalchemy as sa

revision = "20260908_0002"
down_revision = "20260908_0001"
branch_labels = None
depends_on = None


def _create_tables():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_automation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("state IN ('draft','active','paused','retired')", name='ck_agent_automation_rules_state'),
    sa.CheckConstraint('length(display_name) BETWEEN 1 AND 160', name='ck_agent_automation_rules_display_name'),
    sa.CheckConstraint('version > 0', name='ck_agent_automation_rules_version'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'idempotency_key', name='uq_agent_automation_rules_idempotency')
    )
    op.create_index(op.f('ix_agent_automation_rules_agent_id'), 'agent_automation_rules', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_automation_rules_created_at'), 'agent_automation_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_automation_rules_state'), 'agent_automation_rules', ['state'], unique=False)
    op.create_table('agent_action_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("state IN ('draft','active','paused','retired')", name='ck_agent_action_policies_state'),
    sa.CheckConstraint('length(display_name) BETWEEN 1 AND 160', name='ck_agent_action_policies_display_name'),
    sa.CheckConstraint('version > 0', name='ck_agent_action_policies_version'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'idempotency_key', name='uq_agent_action_policies_idempotency')
    )
    op.create_index(op.f('ix_agent_action_policies_agent_id'), 'agent_action_policies', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_action_policies_created_at'), 'agent_action_policies', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_action_policies_state'), 'agent_action_policies', ['state'], unique=False)
    op.create_table('agent_automation_rule_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('agent_revision_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('trigger_config', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('condition_mode', sa.String(length=16), server_default='always', nullable=False),
    sa.Column('condition_config', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('concurrency_key', sa.String(length=255), nullable=True),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('active_from', sa.DateTime(), nullable=True),
    sa.Column('active_until', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("condition_mode IN ('always','keywords','semantic')", name='ck_agent_automation_rule_revisions_condition_mode'),
    sa.CheckConstraint('active_until IS NULL OR active_from IS NULL OR active_until >= active_from', name='ck_agent_automation_rule_revisions_dates'),
    sa.CheckConstraint('length(content_hash) = 64', name='ck_agent_automation_rule_revisions_content_hash'),
    sa.CheckConstraint('length(event_type) BETWEEN 1 AND 80', name='ck_agent_automation_rule_revisions_event_type'),
    sa.CheckConstraint('max_attempts BETWEEN 1 AND 100', name='ck_agent_automation_rule_revisions_max_attempts'),
    sa.CheckConstraint('priority BETWEEN -1000000 AND 1000000', name='ck_agent_automation_rule_revisions_priority'),
    sa.CheckConstraint('version > 0', name='ck_agent_automation_rule_revisions_version_positive'),
    sa.ForeignKeyConstraint(['agent_revision_id'], ['agent_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['agent_automation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'idempotency_key', name='uq_agent_automation_rule_revisions_idempotency'),
    sa.UniqueConstraint('rule_id', 'version', name='uq_agent_automation_rule_revisions_version')
    )
    op.create_index(op.f('ix_agent_automation_rule_revisions_agent_revision_id'), 'agent_automation_rule_revisions', ['agent_revision_id'], unique=False)
    op.create_index(op.f('ix_agent_automation_rule_revisions_concurrency_key'), 'agent_automation_rule_revisions', ['concurrency_key'], unique=False)
    op.create_index(op.f('ix_agent_automation_rule_revisions_content_hash'), 'agent_automation_rule_revisions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_agent_automation_rule_revisions_created_at'), 'agent_automation_rule_revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_automation_rule_revisions_event_type'), 'agent_automation_rule_revisions', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_automation_rule_revisions_priority'), 'agent_automation_rule_revisions', ['priority'], unique=False)
    op.create_index('ix_agent_automation_rule_revisions_rule_created', 'agent_automation_rule_revisions', ['rule_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_automation_rule_revisions_rule_id'), 'agent_automation_rule_revisions', ['rule_id'], unique=False)
    op.create_table('agent_action_policy_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('authorization_mode', sa.String(length=24), server_default='human_approval', nullable=False),
    sa.Column('constraints', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('rate_limit', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('dedupe_window_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fallback_behavior', sa.String(length=24), server_default='require_approval', nullable=False),
    sa.Column('active_from', sa.DateTime(), nullable=True),
    sa.Column('active_until', sa.DateTime(), nullable=True),
    sa.Column('registry_schema_version', sa.String(length=32), server_default='1', nullable=False),
    sa.Column('registry_adapter_key', sa.String(length=128), nullable=True),
    sa.Column('registry_adapter_version', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("authorization_mode IN ('human_approval','bounded_auto')", name='ck_agent_action_policy_revisions_authorization_mode'),
    sa.CheckConstraint("fallback_behavior IN ('require_approval','block')", name='ck_agent_action_policy_revisions_fallback_behavior'),
    sa.CheckConstraint("length(trim(action_type)) BETWEEN 1 AND 80 AND action_type = lower(action_type) AND action_type = trim(action_type) AND action_type NOT LIKE '% %'", name='ck_agent_action_policy_revisions_action_type'),
    sa.CheckConstraint('active_until IS NULL OR active_from IS NULL OR active_until >= active_from', name='ck_agent_action_policy_revisions_dates'),
    sa.CheckConstraint('dedupe_window_seconds >= 0', name='ck_agent_action_policy_revisions_dedupe_window'),
    sa.CheckConstraint('length(content_hash) = 64', name='ck_agent_action_policy_revisions_content_hash'),
    sa.CheckConstraint('version > 0', name='ck_agent_action_policy_revisions_version_positive'),
    sa.ForeignKeyConstraint(['connection_id'], ['external_connections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_id'], ['agent_action_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'idempotency_key', name='uq_agent_action_policy_revisions_idempotency'),
    sa.UniqueConstraint('policy_id', 'version', name='uq_agent_action_policy_revisions_version')
    )
    op.create_index(op.f('ix_agent_action_policy_revisions_action_type'), 'agent_action_policy_revisions', ['action_type'], unique=False)
    op.create_index(op.f('ix_agent_action_policy_revisions_connection_id'), 'agent_action_policy_revisions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_agent_action_policy_revisions_content_hash'), 'agent_action_policy_revisions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_agent_action_policy_revisions_created_at'), 'agent_action_policy_revisions', ['created_at'], unique=False)
    op.create_index('ix_agent_action_policy_revisions_policy_created', 'agent_action_policy_revisions', ['policy_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_action_policy_revisions_policy_id'), 'agent_action_policy_revisions', ['policy_id'], unique=False)
    op.create_table('agent_automation_rule_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_revision_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('action_policy_revision_id', sa.UUID(), nullable=False),
    sa.Column('input_mapping', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('on_noop', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("on_noop IS NULL OR on_noop IN ('continue','stop')", name='ck_agent_automation_rule_actions_on_noop'),
    sa.CheckConstraint('position >= 0', name='ck_agent_automation_rule_actions_position'),
    sa.ForeignKeyConstraint(['action_policy_revision_id'], ['agent_action_policy_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_revision_id'], ['agent_automation_rule_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_revision_id', 'position', name='uq_agent_automation_rule_actions_position')
    )
    op.create_index(op.f('ix_agent_automation_rule_actions_action_policy_revision_id'), 'agent_automation_rule_actions', ['action_policy_revision_id'], unique=False)
    op.create_index(op.f('ix_agent_automation_rule_actions_created_at'), 'agent_automation_rule_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_automation_rule_actions_rule_revision_id'), 'agent_automation_rule_actions', ['rule_revision_id'], unique=False)
    op.create_table('agent_automation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_revision', sa.String(length=160), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('space_id', sa.UUID(), nullable=True),
    sa.Column('conversation_session_id', sa.UUID(), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), server_default='system', nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('service_actor_key', sa.String(length=120), nullable=True),
    sa.Column('safe_metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("actor_kind IN ('human','agent','service','system')", name='ck_agent_automation_events_actor_kind'),
    sa.CheckConstraint('NOT (actor_id IS NOT NULL AND service_actor_key IS NOT NULL)', name='ck_agent_automation_events_actor_fields_xor'),
    sa.CheckConstraint('length(event_hash) = 64', name='ck_agent_automation_events_event_hash'),
    sa.CheckConstraint('length(event_type) BETWEEN 1 AND 80', name='ck_agent_automation_events_event_type'),
    sa.CheckConstraint('length(source_id) BETWEEN 1 AND 255', name='ck_agent_automation_events_source_id'),
    sa.CheckConstraint('length(source_revision) BETWEEN 1 AND 160', name='ck_agent_automation_events_source_revision'),
    sa.CheckConstraint('length(source_type) BETWEEN 1 AND 80', name='ck_agent_automation_events_source_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'source_type', 'source_id', 'source_revision', name='uq_agent_automation_events_source_identity')
    )
    op.create_index(op.f('ix_agent_automation_events_actor_id'), 'agent_automation_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_agent_automation_events_conversation_session_id'), 'agent_automation_events', ['conversation_session_id'], unique=False)
    op.create_index(op.f('ix_agent_automation_events_created_at'), 'agent_automation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_automation_events_event_hash'), 'agent_automation_events', ['event_hash'], unique=False)
    op.create_index(op.f('ix_agent_automation_events_event_type'), 'agent_automation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_automation_events_occurred_at'), 'agent_automation_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_agent_automation_events_project_id'), 'agent_automation_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_automation_events_source_id'), 'agent_automation_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_agent_automation_events_source_revision'), 'agent_automation_events', ['source_revision'], unique=False)
    op.create_index(op.f('ix_agent_automation_events_source_type'), 'agent_automation_events', ['source_type'], unique=False)
    op.create_index(op.f('ix_agent_automation_events_space_id'), 'agent_automation_events', ['space_id'], unique=False)
    op.create_index('ix_agent_automation_events_type_occurred', 'agent_automation_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('agent_automation_discovery_cursors',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('after_rule_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('agent_automation_rule_discovery_cursors',
    sa.Column('rule_revision_id', sa.UUID(), nullable=False),
    sa.Column('after_occurred_at', sa.DateTime(), nullable=True),
    sa.Column('after_event_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('(after_occurred_at IS NULL AND after_event_id IS NULL) OR (after_occurred_at IS NOT NULL AND after_event_id IS NOT NULL)', name='ck_automation_rule_discovery_cursor_pair'),
    sa.ForeignKeyConstraint(['rule_revision_id'], ['agent_automation_rule_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_revision_id')
    )
    op.create_table('integration_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('credential_kind', sa.String(length=64), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=128), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='verification_pending', nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('verification_code', sa.String(length=128), nullable=True),
    sa.Column('capabilities', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('verification_pending','verified','invalid','unsupported','disabled','key_unavailable')", name='ck_integration_credentials_status'),
    sa.CheckConstraint('length(payload_digest) = 64', name='ck_integration_credentials_payload_digest'),
    sa.CheckConstraint('length(state_hash) = 64', name='ck_integration_credentials_state_hash'),
    sa.CheckConstraint('length(trim(credential_kind)) BETWEEN 1 AND 64', name='ck_integration_credentials_kind'),
    sa.CheckConstraint('length(trim(encrypted_payload)) > 0', name='ck_integration_credentials_payload'),
    sa.CheckConstraint('revision > 0', name='ck_integration_credentials_revision'),
    sa.ForeignKeyConstraint(['connection_id'], ['external_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_credentials_connection_id'), 'integration_credentials', ['connection_id'], unique=True)
    op.create_index(op.f('ix_integration_credentials_created_at'), 'integration_credentials', ['created_at'], unique=False)
    op.create_index('ix_integration_credentials_owner_project', 'integration_credentials', ['owner_user_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_integration_credentials_owner_user_id'), 'integration_credentials', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_integration_credentials_project_id'), 'integration_credentials', ['project_id'], unique=False)
    op.create_index(op.f('ix_integration_credentials_status'), 'integration_credentials', ['status'], unique=False)
    op.create_index('ix_integration_credentials_status_updated', 'integration_credentials', ['status', 'updated_at'], unique=False)
    op.create_index(op.f('ix_integration_credentials_updated_at'), 'integration_credentials', ['updated_at'], unique=False)
    op.create_table('integration_credential_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), server_default='human', nullable=False),
    sa.Column('service_actor_key', sa.String(length=120), nullable=True),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('provider_code', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("actor_type IN ('human','service','system')", name='ck_integration_credential_audit_actor_type'),
    sa.CheckConstraint('NOT (actor_id IS NOT NULL AND service_actor_key IS NOT NULL)', name='ck_integration_credential_audit_actor_fields_xor'),
    sa.CheckConstraint('length(event_type) BETWEEN 1 AND 32', name='ck_integration_credential_audit_event_type'),
    sa.CheckConstraint('length(state_hash) = 64', name='ck_integration_credential_audit_state_hash'),
    sa.CheckConstraint('revision > 0', name='ck_integration_credential_audit_revision'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integration_credential_audit_credential_created', 'integration_credential_audit_events', ['credential_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_integration_credential_audit_events_actor_id'), 'integration_credential_audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_integration_credential_audit_events_connection_id'), 'integration_credential_audit_events', ['connection_id'], unique=False)
    op.create_index(op.f('ix_integration_credential_audit_events_created_at'), 'integration_credential_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_integration_credential_audit_events_credential_id'), 'integration_credential_audit_events', ['credential_id'], unique=False)
    op.create_index(op.f('ix_integration_credential_audit_events_event_type'), 'integration_credential_audit_events', ['event_type'], unique=False)
    op.create_table('telephony_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('provider', sa.String(length=32), server_default='openai_realtime_sip', nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('called_number_hash', sa.String(length=64), nullable=True),
    sa.Column('called_number_masked', sa.String(length=32), nullable=True),
    sa.Column('provider_route_ref', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('agent_revision_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('greeting_override', sa.String(length=1200), nullable=True),
    sa.Column('business_hours', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('transfer_policy', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('fallback_mode', sa.String(length=16), server_default='reject', nullable=False),
    sa.Column('fallback_destination_key', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('route_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("fallback_mode <> 'transfer' OR (fallback_destination_key IS NOT NULL AND length(trim(fallback_destination_key)) > 0)", name='ck_telephony_routes_fallback_destination'),
    sa.CheckConstraint("fallback_mode IN ('reject','voicemail','transfer')", name='ck_telephony_routes_fallback'),
    sa.CheckConstraint("state IN ('draft','active','paused','retired')", name='ck_telephony_routes_state'),
    sa.CheckConstraint('called_number_hash IS NULL OR length(called_number_hash) = 64', name='ck_telephony_routes_number_hash'),
    sa.CheckConstraint('length(route_hash) = 64', name='ck_telephony_routes_hash'),
    sa.CheckConstraint('length(trim(display_name)) BETWEEN 1 AND 160', name='ck_telephony_routes_name'),
    sa.CheckConstraint('version > 0', name='ck_telephony_routes_version'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_revision_id'], ['agent_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['connection_id'], ['external_connections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'idempotency_key', name='uq_telephony_routes_idempotency')
    )
    op.create_index(op.f('ix_telephony_routes_agent_id'), 'telephony_routes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_telephony_routes_called_number_hash'), 'telephony_routes', ['called_number_hash'], unique=False)
    op.create_index(op.f('ix_telephony_routes_state'), 'telephony_routes', ['state'], unique=False)
    op.create_index('uq_telephony_routes_active_number', 'telephony_routes', ['provider', 'called_number_hash'], unique=True, sqlite_where=sa.text("state = 'active' AND called_number_hash IS NOT NULL"), postgresql_where=sa.text("state = 'active' AND called_number_hash IS NOT NULL"))
    op.create_index('uq_telephony_routes_active_ref', 'telephony_routes', ['provider', 'provider_route_ref'], unique=True, sqlite_where=sa.text("state = 'active' AND provider_route_ref IS NOT NULL"), postgresql_where=sa.text("state = 'active' AND provider_route_ref IS NOT NULL"))
    op.create_table('telephony_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_call_id', sa.String(length=255), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('route_version', sa.Integer(), nullable=True),
    sa.Column('route_hash', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('agent_revision_id', sa.UUID(), nullable=True),
    sa.Column('conversation_session_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=16), server_default='incoming', nullable=False),
    sa.Column('caller_identity_hash', sa.String(length=64), nullable=True),
    sa.Column('caller_masked', sa.String(length=32), nullable=True),
    sa.Column('called_identity_hash', sa.String(length=64), nullable=True),
    sa.Column('called_masked', sa.String(length=32), nullable=True),
    sa.Column('transfer_destination_key', sa.String(length=120), nullable=True),
    sa.Column('safe_error_code', sa.String(length=128), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("state IN ('incoming','accepting','active','transferred','completed','rejected','failed','uncertain')", name='ck_telephony_calls_state'),
    sa.CheckConstraint("state NOT IN ('accepting','active','transferred','completed') OR (route_id IS NOT NULL AND route_version IS NOT NULL AND route_hash IS NOT NULL AND agent_id IS NOT NULL AND agent_revision_id IS NOT NULL)", name='ck_telephony_calls_route_evidence'),
    sa.CheckConstraint('called_identity_hash IS NULL OR length(called_identity_hash) = 64', name='ck_telephony_calls_called_hash'),
    sa.CheckConstraint('caller_identity_hash IS NULL OR length(caller_identity_hash) = 64', name='ck_telephony_calls_caller_hash'),
    sa.CheckConstraint('route_hash IS NULL OR length(route_hash) = 64', name='ck_telephony_calls_route_hash'),
    sa.CheckConstraint('version > 0 AND (route_version IS NULL OR route_version > 0)', name='ck_telephony_calls_versions'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_session_id'], ['conversation_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_call_id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index(op.f('ix_telephony_calls_agent_id'), 'telephony_calls', ['agent_id'], unique=False)
    op.create_index(op.f('ix_telephony_calls_received_at'), 'telephony_calls', ['received_at'], unique=False)
    op.create_index(op.f('ix_telephony_calls_route_id'), 'telephony_calls', ['route_id'], unique=False)
    op.create_index(op.f('ix_telephony_calls_state'), 'telephony_calls', ['state'], unique=False)
    # ### end Alembic commands ###


_ACTION_CHECKS = {
    "ck_external_actions_type": "length(trim(action_type)) BETWEEN 1 AND 80 AND action_type = lower(action_type) AND action_type = trim(action_type) AND action_type NOT LIKE '% %'",
    "ck_external_actions_authorization_mode": "authorization_mode IN ('human_approval','bounded_policy')",
    "ck_external_actions_credential_revision": "credential_revision IS NULL OR credential_revision > 0",
    "ck_external_actions_action_position": "action_position IS NULL OR action_position >= 0",
    "ck_external_actions_bounded_provenance": "authorization_mode <> 'bounded_policy' OR (action_policy_id IS NOT NULL AND action_policy_revision_id IS NOT NULL AND action_policy_hash IS NOT NULL AND length(action_policy_hash) = 64 AND origin_agent_id IS NOT NULL AND origin_agent_run_id IS NOT NULL AND (automation_rule_revision_id IS NULL OR origin_work_item_id IS NOT NULL))",
    "ck_external_actions_provider_evidence": "execution_mode <> 'provider' OR (adapter_key IS NOT NULL AND length(trim(adapter_key)) > 0 AND adapter_version IS NOT NULL AND length(trim(adapter_version)) > 0 AND credential_state_hash IS NOT NULL AND length(credential_state_hash) = 64 AND execution_key IS NOT NULL AND length(trim(execution_key)) > 0 AND ((action_type NOT LIKE 'media.%' AND action_type <> 'engagement.submit_application' AND registry_schema_version IS NOT NULL AND length(trim(registry_schema_version)) > 0) OR (capability_snapshot_id IS NOT NULL AND capability_snapshot_hash IS NOT NULL AND length(capability_snapshot_hash) = 64)))"
}
_ATTEMPT_CHECKS = {
    "ck_external_action_attempts_executor_type": "executor_type IN ('manual', 'provider', 'service')",
    "ck_external_action_attempts_provider_executor": "execution_mode <> 'provider' OR executor_type IN ('provider','service')",
    "ck_external_action_attempts_provider_evidence": "execution_mode <> 'provider' OR (provider_key IS NOT NULL AND length(trim(provider_key)) > 0 AND provider_adapter_key IS NOT NULL AND length(trim(provider_adapter_key)) > 0 AND provider_adapter_version IS NOT NULL AND length(trim(provider_adapter_version)) > 0 AND credential_state_hash IS NOT NULL AND length(credential_state_hash) = 64 AND execution_key IS NOT NULL AND length(trim(execution_key)) > 0 AND ((registry_schema_version IS NOT NULL AND length(trim(registry_schema_version)) > 0) OR (capability_snapshot_id IS NOT NULL AND capability_snapshot_hash IS NOT NULL AND length(capability_snapshot_hash) = 64)))"
}

# Preserve rows admitted by the predecessor's SQL UNKNOWN/NULL semantics.
# Only the migration may set the marker; triggers below close all new writes.
for _checks in (_ACTION_CHECKS, _ATTEMPT_CHECKS):
    for _name in tuple(_checks):
        if _name.endswith("_provider_evidence"):
            _checks[_name] = "legacy_evidence_incomplete OR " + _checks[_name]


def _mark_legacy_evidence():
    for table in ("external_actions", "external_action_attempts"):
        op.add_column(table, sa.Column("legacy_evidence_incomplete", sa.Boolean(), nullable=False, server_default=sa.false()))
    for table, fields in (
        ("external_actions", ("adapter_key", "adapter_version", "execution_key")),
        ("external_action_attempts", ("provider_key", "provider_adapter_key", "provider_adapter_version", "execution_key")),
    ):
        complete = " AND ".join(f"{field} IS NOT NULL AND length(trim({field})) > 0" for field in fields)
        complete += " AND capability_snapshot_id IS NOT NULL AND capability_snapshot_hash IS NOT NULL AND length(capability_snapshot_hash) = 64"
        complete += " AND credential_state_hash IS NOT NULL AND length(credential_state_hash) = 64"
        op.execute(sa.text(f"UPDATE {table} SET legacy_evidence_incomplete = true WHERE execution_mode = 'provider' AND NOT ({complete})"))
    # An incomplete old attempt also fences its action even if that action's
    # own evidence tuple was complete, without rewriting either row's status.
    op.execute(sa.text("UPDATE external_actions SET legacy_evidence_incomplete = true WHERE id IN (SELECT action_id FROM external_action_attempts WHERE legacy_evidence_incomplete)"))


def _alter_actions():
    bind = op.get_bind()
    # SQLite table replacement otherwise discards existing table triggers.
    trigger_sql = []
    if bind.dialect.name == "sqlite":
        trigger_sql = list(bind.execute(sa.text(
            "SELECT sql FROM sqlite_master WHERE type='trigger' "
            "AND tbl_name IN ('external_actions','external_action_attempts') AND sql IS NOT NULL"
        )).scalars())
    naming = {"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}
    origin_fk_names = []
    for fk in sa.inspect(bind).get_foreign_keys("external_actions"):
        columns = fk["constrained_columns"]
        if len(columns) == 1 and columns[0] in ("origin_agent_id", "origin_agent_run_id", "origin_work_item_id"):
            origin_fk_names.append(fk.get("name") or f"fk_external_actions_{columns[0]}_{fk['referred_table']}")
    with op.batch_alter_table("external_actions", naming_convention=naming) as batch:
        for name in origin_fk_names:
            batch.drop_constraint(name, type_="foreignkey")
        batch.alter_column("action_type", existing_type=sa.String(64), type_=sa.String(80), existing_nullable=False)
        batch.add_column(sa.Column("authorization_mode", sa.String(24), nullable=False, server_default="human_approval"))
        for name in ("action_policy_id", "action_policy_revision_id", "automation_rule_revision_id", "source_event_id"):
            batch.add_column(sa.Column(name, sa.UUID(), nullable=True))
        batch.add_column(sa.Column("action_policy_hash", sa.String(64), nullable=True))
        batch.add_column(sa.Column("dedupe_key", sa.String(255), nullable=True))
        batch.add_column(sa.Column("registry_schema_version", sa.String(32), nullable=True))
        batch.add_column(sa.Column("credential_revision", sa.Integer(), nullable=True))
        batch.add_column(sa.Column("action_position", sa.Integer(), nullable=True))
        for column, target in (
            ("action_policy_id", "agent_action_policies"),
            ("action_policy_revision_id", "agent_action_policy_revisions"),
            ("automation_rule_revision_id", "agent_automation_rule_revisions"),
            ("source_event_id", "agent_automation_events"),
        ):
            batch.create_foreign_key("fk_external_actions_" + column, target, [column], ["id"], ondelete="RESTRICT")
        for name in ("ck_external_actions_type", "ck_external_actions_provider_evidence"):
            batch.drop_constraint(name, type_="check")
        for name, condition in _ACTION_CHECKS.items():
            batch.create_check_constraint(name, condition)
        batch.create_index("ix_external_actions_dedupe_key", ["dedupe_key"])
        batch.create_index("ix_external_actions_policy_dedupe_created", ["action_policy_id", "dedupe_key", "created_at"])
    with op.batch_alter_table("external_action_attempts") as batch:
        batch.alter_column("provider_key", existing_type=sa.String(16), type_=sa.String(120), existing_nullable=True)
        batch.add_column(sa.Column("registry_schema_version", sa.String(32), nullable=True))
        for name, condition in _ATTEMPT_CHECKS.items():
            batch.drop_constraint(name, type_="check")
            batch.create_check_constraint(name, condition)
    for sql in trigger_sql:
        op.execute(sa.text(sql))


_IMMUTABLE = (
    "agent_automation_rule_revisions", "agent_action_policy_revisions",
    "agent_automation_rule_actions", "agent_automation_events",
    "integration_credential_audit_events",
)


def _guards():
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        op.execute("""
            CREATE FUNCTION ai_employee_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN RAISE EXCEPTION 'AI employee evidence is immutable'; END; $$;
        """)
    for table in _IMMUTABLE:
        if dialect == "postgresql":
            op.execute(f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION ai_employee_immutable()")
            op.execute(f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} FOR EACH STATEMENT EXECUTE FUNCTION ai_employee_immutable()")
        elif dialect == "sqlite":
            for operation in ("UPDATE", "DELETE"):
                op.execute(f"CREATE TRIGGER {table}_no_{operation.lower()} BEFORE {operation} ON {table} BEGIN SELECT RAISE(ABORT, 'AI employee evidence is immutable'); END")
    # A schema pin on an attempt must never bypass legacy Media evidence.
    missing = "(NEW.capability_snapshot_id IS NULL OR NEW.capability_snapshot_hash IS NULL OR length(NEW.capability_snapshot_hash) <> 64)"
    legacy = "EXISTS (SELECT 1 FROM external_actions a WHERE a.id = NEW.action_id AND (a.action_type LIKE 'media.%' OR a.action_type = 'engagement.submit_application'))"
    condition = f"NOT NEW.legacy_evidence_incomplete AND NEW.execution_mode = 'provider' AND {missing} AND {legacy}"
    # Route binding can be set once before accept; then it is historical evidence.
    fields = ("route_id", "route_version", "route_hash", "agent_id", "agent_revision_id")
    if dialect == "sqlite":
        for operation in ("INSERT", "UPDATE"):
            op.execute(f"CREATE TRIGGER ai_employee_attempt_legacy_{operation.lower()} BEFORE {operation} ON external_action_attempts WHEN {condition} BEGIN SELECT RAISE(ABORT, 'legacy provider evidence required'); END")
        changed = " OR ".join(f"NEW.{field} IS NOT OLD.{field}" for field in fields)
        op.execute(f"CREATE TRIGGER telephony_call_route_snapshot BEFORE UPDATE ON telephony_calls WHEN (OLD.route_id IS NOT NULL OR OLD.state <> 'incoming') AND ({changed}) BEGIN SELECT RAISE(ABORT, 'call route snapshot is immutable'); END")
    elif dialect == "postgresql":
        op.execute(f"""
            CREATE FUNCTION ai_employee_legacy_attempt() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN IF {condition} THEN RAISE EXCEPTION 'legacy provider evidence required'; END IF; RETURN NEW; END; $$;
        """)
        op.execute("CREATE TRIGGER ai_employee_attempt_legacy BEFORE INSERT OR UPDATE ON external_action_attempts FOR EACH ROW EXECUTE FUNCTION ai_employee_legacy_attempt()")
        changed = " OR ".join(f"NEW.{field} IS DISTINCT FROM OLD.{field}" for field in fields)
        op.execute(f"""
            CREATE FUNCTION telephony_call_snapshot_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN IF (OLD.route_id IS NOT NULL OR OLD.state <> 'incoming') AND ({changed})
            THEN RAISE EXCEPTION 'call route snapshot is immutable'; END IF; RETURN NEW; END; $$;
        """)
        op.execute("CREATE TRIGGER telephony_call_route_snapshot BEFORE UPDATE ON telephony_calls FOR EACH ROW EXECUTE FUNCTION telephony_call_snapshot_guard()")

    _legacy_and_origin_guards()


def _legacy_and_origin_guards():
    """Grandfather only pre-migration rows; preserve flags and origin pins."""
    bind = op.get_bind()
    origin_fields = ("origin_agent_id", "origin_agent_run_id", "origin_work_item_id")
    parent_legacy = "EXISTS (SELECT 1 FROM external_actions a WHERE a.id = NEW.action_id AND a.legacy_evidence_incomplete)"
    if bind.dialect.name == "sqlite":
        origin_changed = " OR ".join(f"NEW.{field} IS NOT OLD.{field}" for field in origin_fields)
        op.execute(f"CREATE TRIGGER external_action_origin_immutable BEFORE UPDATE ON external_actions WHEN {origin_changed} BEGIN SELECT RAISE(ABORT, 'action origin evidence is immutable'); END")
        for table in ("external_actions", "external_action_attempts"):
            columns = [column["name"] for column in sa.inspect(bind).get_columns(table) if column["name"] != "created_by"]
            changed = " OR ".join(f'NEW."{column}" IS NOT OLD."{column}"' for column in columns)
            changed = f"({changed}) OR (NEW.created_by IS NOT OLD.created_by AND NEW.created_by IS NOT NULL)"
            parent_check = f" OR {parent_legacy}" if table == "external_action_attempts" else ""
            op.execute(f"CREATE TRIGGER {table}_legacy_insert BEFORE INSERT ON {table} WHEN NEW.legacy_evidence_incomplete{parent_check} BEGIN SELECT RAISE(ABORT, 'legacy provider evidence is nonexecutable'); END")
            frozen = f"(OLD.legacy_evidence_incomplete{parent_check}) AND ({changed})"
            op.execute(f"CREATE TRIGGER {table}_legacy_update BEFORE UPDATE ON {table} WHEN NEW.legacy_evidence_incomplete IS NOT OLD.legacy_evidence_incomplete OR ({frozen}) BEGIN SELECT RAISE(ABORT, 'legacy provider evidence is nonexecutable'); END")
    elif bind.dialect.name == "postgresql":
        origin_changed = " OR ".join(f"NEW.{field} IS DISTINCT FROM OLD.{field}" for field in origin_fields)
        op.execute(f"""
            CREATE FUNCTION external_action_origin_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN IF {origin_changed} THEN RAISE EXCEPTION 'action origin evidence is immutable'; END IF; RETURN NEW; END; $$;
        """)
        op.execute("CREATE TRIGGER external_action_origin_immutable BEFORE UPDATE ON external_actions FOR EACH ROW EXECUTE FUNCTION external_action_origin_guard()")
        for table in ("external_actions", "external_action_attempts"):
            parent_check = f" OR {parent_legacy}" if table == "external_action_attempts" else ""
            op.execute(f"""
                CREATE FUNCTION {table}_legacy_guard() RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        IF NEW.legacy_evidence_incomplete{parent_check} THEN
                            RAISE EXCEPTION 'legacy provider evidence is nonexecutable';
                        END IF;
                    ELSE
                        IF NEW.legacy_evidence_incomplete IS DISTINCT FROM OLD.legacy_evidence_incomplete
                           OR ((OLD.legacy_evidence_incomplete{parent_check}) AND
                               ((to_jsonb(NEW) - 'created_by') IS DISTINCT FROM (to_jsonb(OLD) - 'created_by')
                                OR (NEW.created_by IS DISTINCT FROM OLD.created_by AND NEW.created_by IS NOT NULL)))
                        THEN RAISE EXCEPTION 'legacy provider evidence is nonexecutable'; END IF;
                    END IF;
                    RETURN NEW;
                END; $$;
            """)
            op.execute(f"CREATE TRIGGER {table}_legacy_guard BEFORE INSERT OR UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION {table}_legacy_guard()")


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name == "sqlite" and bind.exec_driver_sql("PRAGMA foreign_keys").scalar():
        raise RuntimeError("SQLite migration requires foreign_keys OFF before BEGIN; re-enable and run foreign_key_check after upgrade")
    _create_tables()
    _mark_legacy_evidence()
    _alter_actions()
    _guards()


def downgrade():
    # Dropping this schema destroys immutable facts and governance evidence,
    # and generic action rows cannot fit the previous closed action-type check.
    raise RuntimeError("AI employee persistence is forward-only; restore a verified pre-upgrade backup")
