import { StyleSheet } from "react-native";

export const chatScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#11111b" },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#11111b",
  },
  statusChip: { backgroundColor: "#313244", marginRight: 6 },
  statusChipText: { color: "#cdd6f4", fontSize: 11 },
  connectionBar: {
    minHeight: 30,
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 4,
    gap: 7,
    backgroundColor: "#181825",
    borderBottomColor: "#313244",
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  connectionDot: { width: 8, height: 8, borderRadius: 4, flexGrow: 0, flexShrink: 0 },
  connectionLabel: {
    minWidth: 0,
    flexShrink: 1,
    color: "#cdd6f4",
    fontSize: 12,
    fontWeight: "700",
  },
  projectChip: { maxWidth: 132, backgroundColor: "#313244", height: 28 },
  projectChipText: { color: "#cdd6f4", fontSize: 11 },
  projectError: {
    color: "#f38ba8",
    backgroundColor: "#2d1822",
    fontSize: 12,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  pendingBadge: {
    backgroundColor: "#453a2b",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  pendingBadgeText: { color: "#f9e2af", fontSize: 11, fontWeight: "700" },
  commandChip: { backgroundColor: "#181825", marginRight: 6 },
  commandChipText: { color: "#cdd6f4", fontSize: 11 },
  pendingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#181825",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  pendingTextWrap: { flex: 1 },
  pendingTitle: { color: "#cdd6f4", fontSize: 13, fontWeight: "700" },
  pendingMeta: { color: "#a6adc8", fontSize: 11, marginTop: 2 },
  errorBanner: {
    backgroundColor: "#2d1822",
    borderBottomColor: "#f38ba8",
    borderBottomWidth: 1,
    padding: 10,
  },
  errorText: { color: "#f38ba8", fontSize: 13 },
  messageList: { paddingHorizontal: 14, paddingTop: 16, paddingBottom: 12 },
  empty: { alignItems: "center", paddingTop: 60 },
  emptyText: { color: "#a6adc8", fontSize: 14 },
  messageWrap: { marginBottom: 8 },
  messageBubble: {
    marginBottom: 8,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 18,
    maxWidth: "88%",
  },
  userBubble: { alignSelf: "flex-end", backgroundColor: "#2d2d3d" },
  assistantBubble: {
    alignSelf: "stretch",
    backgroundColor: "transparent",
    maxWidth: "100%",
    paddingHorizontal: 2,
  },
  userText: { color: "#cdd6f4", fontSize: 15 },
  cancelledLabel: { color: "#f9a8d4", fontSize: 12, fontWeight: "600", marginBottom: 6 },
  cancelledLogCard: {
    backgroundColor: "#181825",
    borderColor: "#45475a",
    borderWidth: 1,
    borderRadius: 12,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  attachmentMetadataList: {
    marginTop: 8,
    borderTopColor: "#313244",
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: 6,
  },
  attachmentMetadataRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  attachmentMetadataName: { flex: 1, color: "#89b4fa", fontSize: 12 },
  attachmentMetadataDetail: { color: "#a6adc8", fontSize: 10 },
  cancelledLogTitle: { color: "#cba6f7", fontSize: 12, fontWeight: "700", marginBottom: 7 },
  cancelledLogRow: { borderLeftColor: "#585b70", borderLeftWidth: 2, marginBottom: 8, paddingLeft: 9 },
  cancelledLogAction: { color: "#cdd6f4", fontSize: 12 },
  cancelledLogDetail: { color: "#a6adc8", fontFamily: "monospace", fontSize: 11, marginTop: 3 },
  branchRow: { flexDirection: "row", alignItems: "center", justifyContent: "flex-end", marginTop: -10 },
  branchText: { color: "#a6adc8", fontSize: 12 },
  eventCard: { backgroundColor: "#181825", borderColor: "#313244", borderWidth: 1, borderRadius: 8, padding: 12, marginBottom: 10 },
  eventHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  eventTitle: { flex: 1, color: "#cdd6f4", fontSize: 14, fontWeight: "700" },
  eventDescription: { color: "#a6adc8", fontSize: 13, lineHeight: 18, marginTop: 6 },
  eventMeta: { color: "#a6adc8", fontSize: 12, lineHeight: 17, marginTop: 8, backgroundColor: "#11111b", padding: 8, borderRadius: 6 },
  eventChip: { backgroundColor: "#313244" },
  eventChipText: { color: "#cdd6f4", fontSize: 10 },
  dangerText: { color: "#f38ba8" },
  eventActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8, marginTop: 10 },
  progress: { height: 6, borderRadius: 6, marginTop: 10, backgroundColor: "#313244" },
  inputBar: { backgroundColor: "#11111b", paddingHorizontal: 10, paddingTop: 6 },
  composerStatus: { flexDirection: "row", alignItems: "center", marginHorizontal: 48, marginBottom: 2 },
  composerStatusText: { flex: 1, color: "#a6adc8", fontSize: 11 },
  clearCommandButton: { margin: 0 },
  composerError: { color: "#f38ba8", fontSize: 12, paddingHorizontal: 6, paddingTop: 4 },
  composerSyncStatus: { color: "#a6adc8", fontSize: 11, paddingHorizontal: 6, paddingTop: 3 },
  composerSyncWarning: { color: "#f9e2af", fontSize: 11, paddingHorizontal: 6, paddingTop: 3 },
  slashSuggestions: { backgroundColor: "#181825", borderColor: "#45475a", borderWidth: 1, borderRadius: 10, marginBottom: 4, overflow: "hidden" },
  slashSuggestionRow: { flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 10, paddingVertical: 9, borderBottomColor: "#313244", borderBottomWidth: StyleSheet.hairlineWidth },
  slashCommand: { color: "#c084fc", fontSize: 13, fontWeight: "700" },
  slashDescription: { flex: 1, color: "#a6adc8", fontSize: 12 },
  composerCard: { backgroundColor: "#1e1e2e", borderColor: "#45475a", borderWidth: 1, borderRadius: 24, overflow: "hidden" },
  textInput: { backgroundColor: "#1e1e2e", fontSize: 15, minHeight: 54, maxHeight: 120, paddingHorizontal: 8 },
  composerActions: { minHeight: 48, flexDirection: "row", alignItems: "center", paddingHorizontal: 4, paddingBottom: 4 },
  composerIconButton: { margin: 0 },
  composerSelector: { minWidth: 0, maxWidth: 116, flexShrink: 1, flexDirection: "row", alignItems: "center", paddingHorizontal: 7, paddingVertical: 7 },
  composerSelectorText: { minWidth: 0, flexShrink: 1, color: "#cdd6f4", fontSize: 12, fontWeight: "600" },
  composerSelectorChevron: { color: "#a6adc8", fontSize: 13, marginLeft: 2 },
  composerSelectorDisabled: { color: "#585b70" },
  sendButton: { margin: 2, marginLeft: "auto" },
  dialog: { backgroundColor: "#1e1e2e" },
  dialogTitle: { color: "#cdd6f4" },
  dialogError: { color: "#f38ba8", fontSize: 12, marginTop: 8 },
  menuContent: { backgroundColor: "#1e1e2e" },
  dialogHelp: { color: "#a6adc8", fontSize: 13, marginBottom: 8 },
  modeButton: { marginTop: 8 },
  providerButtonContent: { flexDirection: "row-reverse", justifyContent: "space-between" },
  editInput: { backgroundColor: "#313244", marginTop: 8 },
  dialogScrollArea: { maxHeight: 460, borderColor: "#313244" },
  dialogScrollContent: { paddingVertical: 4 },
  commandRow: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 10, backgroundColor: "transparent" },
  commandText: { flex: 1 },
  commandSectionTitle: { color: "#c084fc", fontSize: 12, fontWeight: "700", marginTop: 4, marginBottom: 2 },
  commandTitle: { color: "#cdd6f4", fontSize: 14, fontWeight: "600" },
  commandDescription: { color: "#a6adc8", fontSize: 12, marginTop: 2 },
  quickActionContent: { justifyContent: "flex-start" },
  diagnosticsText: { color: "#a6adc8", fontSize: 12, lineHeight: 18 },
  innerDivider: { backgroundColor: "#313244", marginVertical: 8 },
});

export const markdownStyles = {
  body: { color: "#cdd6f4", fontSize: 15 },
  heading1: { color: "#cdd6f4", fontWeight: "bold" as const },
  heading2: { color: "#cdd6f4", fontWeight: "bold" as const },
  heading3: { color: "#cdd6f4", fontWeight: "bold" as const },
  code_inline: { backgroundColor: "#313244", color: "#a6e3a1", padding: 2 },
  code_block: { backgroundColor: "#313244", color: "#a6e3a1", padding: 8, borderRadius: 6 },
  fence: { backgroundColor: "#313244", color: "#a6e3a1", padding: 8, borderRadius: 6 },
  link: { color: "#89b4fa" },
  blockquote: { borderLeftColor: "#7c3aed", borderLeftWidth: 3, paddingLeft: 8 },
  bullet_list_icon: { color: "#7c3aed" },
  ordered_list_icon: { color: "#7c3aed" },
};
