"""Database models for conversation memory management

ドメイン別モジュールに分割したモデルパッケージ。公開APIは従来どおり
``from src.memory.models import <Model>`` で全モデル名を提供する。
"""

from sqlalchemy.orm import configure_mappers

from .base import Base
from .agent_automation import (
    AgentAutomationRule, AgentAutomationRuleRevision, AgentAutomationRuleAction,
    AgentAutomationEvent, AgentActionPolicy, AgentActionPolicyRevision,
    AgentAutomationDiscoveryCursor, AgentAutomationRuleDiscoveryCursor,
    AGENT_AUTOMATION_RULE_STATES, AGENT_AUTOMATION_CONDITION_MODES,
    AGENT_AUTOMATION_EVENT_ACTOR_KINDS, AGENT_ACTION_POLICY_STATES,
    AGENT_ACTION_POLICY_AUTHORIZATION_MODES, AGENT_ACTION_POLICY_FALLBACK_BEHAVIORS,
)
from .integration_credentials import (
    IntegrationCredential, IntegrationCredentialAuditEvent,
    INTEGRATION_CREDENTIAL_STATUSES, INTEGRATION_CREDENTIAL_AUDIT_EVENTS,
)
from .telephony import (
    TelephonyRoute, TelephonyCall, TELEPHONY_ROUTE_STATES,
    TELEPHONY_CALL_STATES, TELEPHONY_FALLBACK_MODES,
)
from .conversations import (
    ConversationSession,
    ConversationParticipant,
    ConversationMessage,
    ConversationArchive,
    ConversationHistory,
    public_session_context,
)
from .generated_media import GeneratedMedia
from .audit import ContentDeletionEvent
from .trpg_play import (
    TrpgPlayEvent,
    TrpgPlayParticipant,
    TrpgPlayPrivateState,
    TrpgPlaySession,
    TrpgPlayWhisper,
    TrpgPlayWhisperRecipient,
)
from .agent_runs import (
    AgentRun,
    AgentRunEdge,
    AgentRunEvent,
    AgentRunToolCall,
    ConversationDispatchOutbox,
)
from .agent_work import (
    AGENT_WORK_ACTOR_KINDS,
    AGENT_WORK_ITEM_STATES,
    AGENT_WORK_OUTCOME_CLASSES,
    AGENT_WORK_STATES,
    AgentWorkEvent,
    AgentWorkItem,
)
from .agent_identity import (
    AGENT_STATES,
    AGENT_ASSIGNMENT_STATES,
    AGENT_SPACE_ASSIGNMENT_KINDS,
    AGENT_PROJECT_ROLES,
    AGENT_TASK_ASSIGNMENT_ROLES,
    PERSONA_OPERATOR_ROLES,
    AUTONOMY_LEVELS,
    EMPLOYMENT_STATES,
    Organization,
    OrganizationSettings,
    Agent,
    AgentRevision,
    AgentOrganizationProfile,
    AgentSpaceAssignment,
    AgentProjectGrant,
    AgentTaskAssignment,
    PersonaOperatorAssignment,
)
from .skill_learning import (
    SkillProposal,
    SkillProposalHistory,
    SkillUsageReceipt,
)
from .users import (
    User,
    ExternalIdentityBinding,
    ScopedMemoryPrincipal,
    LongLivedApiToken,
    UserHfCredential,
    UserHydrusCredential,
    UserXCookieCredential,
    WebUILoginLog,
    AppConfigSetting,
    FileExplorerBookmark,
    FileExplorerLauncher,
    GoogleCalendarConnection,
    WebexConnection,
    WebexSpaceSelection,
    Feedback,
)
from .automation import HeartbeatRunState
from .media_operations_automation import (
    AUTOMATION_EXECUTION_MODE_VALUES, AUTOMATION_RUN_STATE_VALUES, AUTOMATION_NOVELTY_POLICY_VALUES,
    AutomationProgram, AutomationProgramRevision, AutomationRun,
)
from .heartbeat_history import (
    HEARTBEAT_HISTORY_STATUSES,
    HeartbeatHistoryEntry,
    HeartbeatRunHistory,
    HeartbeatRunRecord,
)
from .enterprise import EnterpriseBootstrapState
from .spotify import (
    SpotifyActivityLog,
    SpotifySessionSummary,
)
from .projects import (
    Space,
    Project,
    ProjectKnowledgeRef,
    ProjectOverview,
    ProjectOverviewRefreshJob,
    ContextMemory,
    ContextMemoryAudit,
    ScopedMemoryJob,
    DreamingMemoryState,
    DreamingMemoryRun,
    ProjectMember,
    ProjectQaEntry,
    ProjectJoinRequest,
)
from .knowledge_capture import (
    DEFAULT_KNOWLEDGE_CAPTURE_MODE,
    KNOWLEDGE_CAPTURE_CANDIDATE_STATES,
    KNOWLEDGE_CAPTURE_CANDIDATE_TERMINAL_STATES,
    KNOWLEDGE_CAPTURE_MODES,
    KNOWLEDGE_CAPTURE_QUEUED_STATE,
    KNOWLEDGE_CAPTURE_QUESTION_STATES,
    KNOWLEDGE_CAPTURE_QUESTION_TERMINAL_STATES,
    MAX_KNOWLEDGE_CAPTURE_QUESTION_ROUNDS,
    KnowledgeCaptureCandidate,
    KnowledgeCaptureQuestion,
    ProjectKnowledgeCaptureSetting,
    normalize_knowledge_capture_mode,
    normalize_candidate_state,
    validate_candidate_transition,
    validate_question_transition,
)
from .meeting_processing import MeetingProcessingJob
from .records import (
    RecordTable,
    RecordField,
    RecordRow,
    RecordView,
    RecordAttachment,
    RecordEvent,
)
from .tasks import (
    LocalTask,
    TaskEvent,
    TaskExecutionSession,
    Task,
    ProjectSchedulePhase,
    TaskSchedulePlacement,
    TaskAssignee,
    TaskComment,
    TaskAttachment,
    TaskReference,
    TaskRelation,
    TaskActivity,
    TaskDependency,
    TaskRecurrenceRule,
    TaskRecurrenceScheduleSegment,
    TaskOccurrence,
    TimeEntry,
    Tag,
    TaskTag,
)
from .notifications import (
    ProjectNotificationSetting,
    NotificationDelivery,
    WebPushSubscription,
)
from .docs_agent import (
    DocsAuthorityState, DocsLibraryRevision, DocsIndexQueue, DocsReadLease,
    DocsEditReadSession,
    DocsMutationReceipt, DocsCoverageRun,
)
from .knowledge import (
    ClipIngestReceipt,
    DocsClipIngestJob,
    DocsCandidate,
    KnowledgeAiSuggestion,
    KnowledgeAttachment,
    KnowledgeEdge,
    KnowledgeField,
    KnowledgeFieldValue,
    KnowledgeImportItem,
    KnowledgeImportJob,
    KnowledgeNode,
    KnowledgeNodeShare,
    KnowledgeNodePlacement,
    KnowledgeNodeSupertag,
    KnowledgeRevision,
    KnowledgeSavedView,
    KnowledgeSearchIndex,
    KnowledgeSource,
    KnowledgeSourcePermission,
    KnowledgeDocument,
    KnowledgeChunk,
    KnowledgeLink,
    KnowledgeAnnotation,
    KnowledgeEditEvent,
    KnowledgeSupertag,
    KnowledgeSupertagField,
    DocsLibrary,
    KnowledgeWorkspace,
)
from .remote import (
    RemoteServerProfile,
)
from .free_team import (
    FreeTeamCandidateModel,
    FreeTeamCredentialProfile,
    FreeTeamQuotaPool,
    FreeTeamReservation,
)
from .yomi import YomiDictionaryEntry, YomiDictionarySync, YomiUnresolvedCandidate
from .apps import (
    App,
    AppArtifact,
    AppGrant,
    AppJob,
    AppRelease,
    AppTarget,
    ProjectApp,
    TaskAppLink,
)
from .managed_tools import (
    MANAGED_TOOL_RUNTIMES,
    MANAGED_TOOL_STATUSES,
    ManagedToolLineage,
    ManagedToolRevision,
    ManagedToolObservation,
    ManagedToolPromotionAudit,
    ManagedScriptLineage,
    ManagedScriptRevision,
    ManagedScriptObservation,
    ManagedScriptPromotionAudit,
    ManagedTool,
)
from .project_storage_operations import ProjectStorageOperation
from .story import (
    StoryWork,
    StoryEpisode,
    StoryLink,
    StoryCharacter,
    StoryWorkCharacter,
    StoryRulebook,
    StoryWorkRulebook,
    StoryNote,
    StoryEpisodeRevision,
    StorySearchIndex,
    StoryGenerationJob,
    StoryIllustration,
    StoryWritingSession,
)
from .operations import (
    ExternalConnection,
    ArtifactVersion,
    EngagementOpportunity,
    Opportunity,
    OpportunityEvaluation,
    Evaluation,
    ApplicationDraft,
    ExternalAction,
    ExternalActionApproval,
    ActionApproval,
    ExternalActionAttempt,
    ActionAttempt,
    ExternalActionReceipt,
    ActionReceipt,
    OperationEvent,
    TimelineEvent,
)
from .media_operations import (
    MEDIA_PLATFORM_VALUES,
    MediaPlatform,
    Persona,
    PersonaRevision,
    PersonaResource,
    PersonaIntakeSlot,
)
from .media_operations_setup import (
    DRAFT_FACT_STATE_VALUES,
    PLATFORM_CAPABILITY_STATUS_VALUES,
    PLATFORM_CREDENTIAL_STATUS_VALUES,
    DraftFactState,
    PlatformCapabilityStatus,
    PlatformCredentialStatus,
    PersonaBulkDraft,
    PersonaBulkDraftSlot,
    PlatformAccount,
    PlatformAccountRevision,
)
from .media_operations_credentials import (
    MEDIA_CREDENTIAL_AUDIT_EVENTS,
    MEDIA_CREDENTIAL_CAPABILITY_VALUES,
    MEDIA_CREDENTIAL_CONNECTION_TYPES,
    MEDIA_CREDENTIAL_STATUSES,
    MediaCredentialConnectionType,
    MediaCredentialStatus,
    MediaPlatformCredential,
    MediaPlatformCredentialAuditEvent,
    media_credential_state_hash,
)
from .media_provider_capability import (
    MEDIA_PROVIDER_CAPABILITY_ACCOUNT_ELIGIBILITY,
    MEDIA_PROVIDER_CAPABILITY_OPERATIONS,
    MEDIA_PROVIDER_CAPABILITY_STATUSES,
    MediaCapabilitySnapshot,
    MediaProviderCapabilitySnapshot,
    ProviderCapabilitySnapshot,
)
from .media_operations_research import (
    RESEARCH_FINDING_KIND_VALUES,
    ResearchFindingKind,
    ResearchRoutine,
    ResearchRoutineRevision,
    ResearchRun,
    ResearchFinding,
    ResearchFindingEvidence,
    EditorialProgram,
    EditorialProgramRevision,
    ContentItem,
    ResearchCandidate,
    RESEARCH_CANDIDATE_STATUS_VALUES,
    RESEARCH_CANDIDATE_DECISION_EVENT_VALUES,
    RESEARCH_CANDIDATE_DECISION_ACTOR_TYPES,
    ResearchCandidateDecision,
    ContentItemFinding,
)
from .media_operations_generation import (
    GENERATION_WORKSPACE_STATUS_VALUES,
    CREATIVE_RECIPE_TYPE_VALUES,
    GENERATION_PLAN_STATUS_VALUES,
    GENERATION_RUN_INTENT_STATUS_VALUES,
    GENERATION_RUN_STATUS_VALUES,
    GenerationWorkspaceStatus,
    CreativeRecipeType,
    GenerationPlanStatus,
    GenerationRunIntentStatus,
    GenerationRunStatus,
    GenerationWorkspace,
    CreativeRecipe,
    CreativeRecipeRevision,
    GenerationPlan,
    GenerationRunIntent,
    GenerationRun,
    GenerationRunObservation,
    GenerationOutput,
    GenerationOutputSelection,
)
from .media_operations_content import (
    CONTENT_VARIANT_PLATFORM_VALUES,
    ContentVariantPlatform,
    QA_ASSESSMENT_RESULT_VALUES,
    QAAssessmentResult,
    RIGHTS_ASSESSMENT_RESULT_VALUES,
    RightsAssessmentResult,
    ContentVariant,
    ContentVariantRevision,
    QAAssessment,
    RightsAssessment,
)
from .media_operations_metrics import (
    MetricSnapshotSource,
    METRIC_SNAPSHOT_SOURCE_VALUES,
    MetricCompleteness,
    METRIC_COMPLETENESS_VALUES,
    MetricIngestionStatus,
    METRIC_INGESTION_STATUS_VALUES,
    ExperimentStatus,
    EXPERIMENT_STATUS_VALUES,
    ExperimentResultStatus,
    EXPERIMENT_RESULT_STATUS_VALUES,
    ExperimentAnalysisDesign,
    EXPERIMENT_ANALYSIS_DESIGN_VALUES,
    DEFAULT_EXPERIMENT_ANALYSIS_METHOD,
    DEFAULT_EXPERIMENT_ANALYSIS_VERSION,
    RevenueEventType,
    REVENUE_EVENT_TYPE_VALUES,
    MetricSnapshot,
    MetricsSnapshot,
    MetricIngestionRunStatus,
    METRIC_INGESTION_RUN_STATUS_VALUES,
    MediaMetricIngestionRun,
    Experiment,
    ExperimentResult,
    ExperimentResultMetricInput,
    ExperimentResultInput,
    ExperimentMetricInput,
    MetricSnapshotInput,
    RevenueEvent,
)
from .media_operations_learning import (
    LearningProposalStatus,
    LEARNING_PROPOSAL_STATUS_VALUES,
    LearningProposal,
)
from .verification import (
    VERIFICATION_ARTIFACT_CLEANUP_STATUSES,
    VERIFICATION_CLEANUP_ITEM_STATUSES,
    VERIFICATION_CLEANUP_STATUSES,
    VERIFICATION_PROVENANCE_SCHEMA_VERSION,
    VERIFICATION_RUN_STATUSES,
    VerificationArtifactProvenance,
    VerificationCleanupItem,
    VerificationCleanupRun,
    VerificationRun,
)
# ECC's Character table shares this Base but lives in ``src.models`` for
# historical reasons.  Import it before final mapper configuration so the
# optional Agent -> Character foreign key is present in full metadata.  The
# guarded import keeps the legacy direct ``src.models.ecc_models`` bootstrap
# cycle safe: that module may still be defining Character at this point.
try:  # pragma: no cover - import order depends on the entry point
    from ...models.ecc_models import Character  # noqa: F401
except (ImportError, AttributeError):
    # ``src.models.ecc_models`` may be the module currently importing us.  It
    # will finish defining Character immediately after this package returns;
    # avoid publishing a misleading ``Character = None`` sentinel.
    pass
configure_mappers()


def __getattr__(name):
    """Lazily expose ECC Character after an import-order cycle."""

    if name == "Character":
        from ...models.ecc_models import Character as _Character

        globals()[name] = _Character
        return _Character
    raise AttributeError(name)

__all__ = [
    "DocsAuthorityState", "DocsLibraryRevision", "DocsIndexQueue", "DocsReadLease",
    "DocsEditReadSession",
    "DocsMutationReceipt", "DocsCoverageRun",
    "AgentAutomationRule", "AgentAutomationRuleRevision", "AgentAutomationRuleAction",
    "AgentAutomationEvent", "AgentActionPolicy", "AgentActionPolicyRevision",
    "AgentAutomationDiscoveryCursor", "AgentAutomationRuleDiscoveryCursor",
    "IntegrationCredential", "IntegrationCredentialAuditEvent", "TelephonyRoute", "TelephonyCall",
    "AGENT_AUTOMATION_RULE_STATES", "AGENT_AUTOMATION_CONDITION_MODES",
    "AGENT_AUTOMATION_EVENT_ACTOR_KINDS", "AGENT_ACTION_POLICY_STATES",
    "AGENT_ACTION_POLICY_AUTHORIZATION_MODES", "AGENT_ACTION_POLICY_FALLBACK_BEHAVIORS",
    "INTEGRATION_CREDENTIAL_STATUSES", "INTEGRATION_CREDENTIAL_AUDIT_EVENTS",
    "TELEPHONY_ROUTE_STATES", "TELEPHONY_CALL_STATES", "TELEPHONY_FALLBACK_MODES",
    "Organization",
    "OrganizationSettings",
    "Agent",
    "AgentRevision",
    "AgentOrganizationProfile",
    "AgentSpaceAssignment",
    "AgentProjectGrant",
    "AgentTaskAssignment",
    "PersonaOperatorAssignment",
    "AGENT_STATES",
    "AGENT_ASSIGNMENT_STATES",
    "AGENT_SPACE_ASSIGNMENT_KINDS",
    "AGENT_PROJECT_ROLES",
    "AGENT_TASK_ASSIGNMENT_ROLES",
    "PERSONA_OPERATOR_ROLES",
    "AUTONOMY_LEVELS",
    "EMPLOYMENT_STATES",
    "AgentRun",
    "AgentRunEdge",
    "AgentRunEvent",
    "AgentRunToolCall",
    "ConversationDispatchOutbox",
    "AgentWorkItem",
    "AgentWorkEvent",
    "AGENT_WORK_STATES",
    "AGENT_WORK_ITEM_STATES",
    "AGENT_WORK_OUTCOME_CLASSES",
    "AGENT_WORK_ACTOR_KINDS",
    "SkillProposal",
    "SkillProposalHistory",
    "SkillUsageReceipt",
    "AppConfigSetting",
    "Base",
    "ContextMemory",
    "ContextMemoryAudit",
    "DreamingMemoryState",
    "DreamingMemoryRun",
    "ConversationArchive",
    "ConversationHistory",
    "ConversationMessage",
    "GeneratedMedia",
    "ContentDeletionEvent",
    "ConversationParticipant",
    "ConversationSession",
    "public_session_context",
    "Feedback",
    "EnterpriseBootstrapState",
    "FileExplorerBookmark",
    "FileExplorerLauncher",
    "FreeTeamCandidateModel",
    "FreeTeamCredentialProfile",
    "FreeTeamQuotaPool",
    "FreeTeamReservation",
    "GoogleCalendarConnection",
    "HeartbeatRunState",
    "AUTOMATION_EXECUTION_MODE_VALUES",
    "AUTOMATION_RUN_STATE_VALUES",
    "AUTOMATION_NOVELTY_POLICY_VALUES",
    "AutomationProgram",
    "AutomationProgramRevision",
    "AutomationRun",
    "HeartbeatRunHistory",
    "HeartbeatRunRecord",
    "HeartbeatHistoryEntry",
    "HEARTBEAT_HISTORY_STATUSES",
    "KnowledgeAnnotation",
    "ClipIngestReceipt",
    "DocsClipIngestJob",
    "DocsCandidate",
    "KnowledgeAiSuggestion",
    "KnowledgeAttachment",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "KnowledgeEdge",
    "KnowledgeEditEvent",
    "KnowledgeField",
    "KnowledgeFieldValue",
    "KnowledgeImportItem",
    "KnowledgeImportJob",
    "KnowledgeLink",
    "KnowledgeNode",
    "KnowledgeNodeShare",
    "KnowledgeNodePlacement",
    "KnowledgeNodeSupertag",
    "KnowledgeRevision",
    "KnowledgeSavedView",
    "KnowledgeSearchIndex",
    "KnowledgeSource",
    "KnowledgeSourcePermission",
    "KnowledgeSupertag",
    "KnowledgeSupertagField",
    "DocsLibrary",
    "KnowledgeWorkspace",
    "LocalTask",
    "LongLivedApiToken",
    "NotificationDelivery",
    "WebPushSubscription",
    "Project",
    "ProjectOverview",
    "ProjectOverviewRefreshJob",
    "ProjectJoinRequest",
    "ProjectKnowledgeCaptureSetting",
    "KnowledgeCaptureCandidate",
    "KnowledgeCaptureQuestion",
    "KNOWLEDGE_CAPTURE_MODES",
    "KNOWLEDGE_CAPTURE_QUEUED_STATE",
    "DEFAULT_KNOWLEDGE_CAPTURE_MODE",
    "KNOWLEDGE_CAPTURE_CANDIDATE_STATES",
    "KNOWLEDGE_CAPTURE_CANDIDATE_TERMINAL_STATES",
    "KNOWLEDGE_CAPTURE_QUESTION_STATES",
    "KNOWLEDGE_CAPTURE_QUESTION_TERMINAL_STATES",
    "MAX_KNOWLEDGE_CAPTURE_QUESTION_ROUNDS",
    "normalize_knowledge_capture_mode",
    "normalize_candidate_state",
    "validate_candidate_transition",
    "validate_question_transition",
    "MeetingProcessingJob",
    "ProjectMember",
    "ProjectNotificationSetting",
    "ProjectQaEntry",
    "RecordAttachment",
    "RecordEvent",
    "RecordField",
    "RecordRow",
    "RecordTable",
    "RecordView",
    "RemoteServerProfile",
    "Space",
    "ScopedMemoryJob",
    "SpotifyActivityLog",
    "SpotifySessionSummary",
    "Tag",
    "Task",
    "ProjectSchedulePhase",
    "TaskSchedulePlacement",
    "TaskActivity",
    "TaskAssignee",
    "TaskAttachment",
    "TaskReference",
    "TaskRelation",
    "TaskComment",
    "TaskDependency",
    "TaskEvent",
    "TaskExecutionSession",
    "TaskOccurrence",
    "TaskRecurrenceRule",
    "TaskRecurrenceScheduleSegment",
    "TaskTag",
    "TimeEntry",
    "User",
    "ExternalIdentityBinding",
    "ScopedMemoryPrincipal",
    "UserHfCredential",
    "UserHydrusCredential",
    "UserXCookieCredential",
    "WebexConnection",
    "WebexSpaceSelection",
    "WebUILoginLog",
    "YomiDictionaryEntry",
    "YomiDictionarySync",
    "YomiUnresolvedCandidate",
    "App",
    "AppArtifact",
    "AppGrant",
    "AppJob",
    "AppRelease",
    "AppTarget",
    "ProjectApp",
    "TaskAppLink",
    "MANAGED_TOOL_RUNTIMES",
    "MANAGED_TOOL_STATUSES",
    "ManagedToolLineage",
    "ManagedToolRevision",
    "ManagedToolObservation",
    "ManagedToolPromotionAudit",
    "ManagedScriptLineage",
    "ManagedScriptRevision",
    "ManagedScriptObservation",
    "ManagedScriptPromotionAudit",
    "ManagedTool",
    "ProjectStorageOperation",
    "StoryWork",
    "StoryEpisode",
    "StoryLink",
    "StoryCharacter",
    "StoryWorkCharacter",
    "StoryRulebook",
    "StoryWorkRulebook",
    "StoryNote",
    "StoryEpisodeRevision",
    "StorySearchIndex",
    "StoryGenerationJob",
    "StoryIllustration",
    "StoryWritingSession",
    "TrpgPlaySession",
    "TrpgPlayParticipant",
    "TrpgPlayEvent",
    "TrpgPlayPrivateState",
    "TrpgPlayWhisper",
    "TrpgPlayWhisperRecipient",
    "ExternalConnection",
    "ArtifactVersion",
    "EngagementOpportunity",
    "Opportunity",
    "OpportunityEvaluation",
    "Evaluation",
    "ApplicationDraft",
    "ExternalAction",
    "ExternalActionApproval",
    "ActionApproval",
    "ExternalActionAttempt",
    "ActionAttempt",
    "ExternalActionReceipt",
    "ActionReceipt",
    "OperationEvent",
    "TimelineEvent",
    "MEDIA_PLATFORM_VALUES",
    "MediaPlatform",
    "Persona",
    "PersonaRevision",
    "PersonaResource",
    "PersonaIntakeSlot",
    "DRAFT_FACT_STATE_VALUES",
    "PLATFORM_CAPABILITY_STATUS_VALUES",
    "PLATFORM_CREDENTIAL_STATUS_VALUES",
    "DraftFactState",
    "PlatformCapabilityStatus",
    "PlatformCredentialStatus",
    "PersonaBulkDraft",
    "PersonaBulkDraftSlot",
    "PlatformAccount",
    "PlatformAccountRevision",
    "MEDIA_CREDENTIAL_AUDIT_EVENTS",
    "MEDIA_CREDENTIAL_CAPABILITY_VALUES",
    "MEDIA_CREDENTIAL_CONNECTION_TYPES",
    "MEDIA_CREDENTIAL_STATUSES",
    "MediaCredentialConnectionType",
    "MediaCredentialStatus",
    "MediaPlatformCredential",
    "MediaPlatformCredentialAuditEvent",
    "media_credential_state_hash",
    "MEDIA_PROVIDER_CAPABILITY_ACCOUNT_ELIGIBILITY",
    "MEDIA_PROVIDER_CAPABILITY_OPERATIONS",
    "MEDIA_PROVIDER_CAPABILITY_STATUSES",
    "MediaCapabilitySnapshot",
    "MediaProviderCapabilitySnapshot",
    "ProviderCapabilitySnapshot",
    "MetricIngestionRunStatus",
    "METRIC_INGESTION_RUN_STATUS_VALUES",
    "MediaMetricIngestionRun",
    "RESEARCH_FINDING_KIND_VALUES",
    "ResearchFindingKind",
    "ResearchRoutine",
    "ResearchRoutineRevision",
    "ResearchRun",
    "ResearchFinding",
    "ResearchFindingEvidence",
    "ResearchCandidate",
    "ResearchCandidateDecision",
    "RESEARCH_CANDIDATE_STATUS_VALUES",
    "RESEARCH_CANDIDATE_DECISION_EVENT_VALUES",
    "RESEARCH_CANDIDATE_DECISION_ACTOR_TYPES",
    "EditorialProgram",
    "EditorialProgramRevision",
    "ContentItem",
    "ContentItemFinding",
    "GENERATION_WORKSPACE_STATUS_VALUES",
    "CREATIVE_RECIPE_TYPE_VALUES",
    "GENERATION_PLAN_STATUS_VALUES",
    "GENERATION_RUN_INTENT_STATUS_VALUES",
    "GENERATION_RUN_STATUS_VALUES",
    "GenerationWorkspaceStatus",
    "CreativeRecipeType",
    "GenerationPlanStatus",
    "GenerationRunIntentStatus",
    "GenerationRunStatus",
    "GenerationWorkspace",
    "CreativeRecipe",
    "CreativeRecipeRevision",
    "GenerationPlan",
    "GenerationRunIntent",
    "GenerationRun",
    "GenerationRunObservation",
    "GenerationOutput",
    "GenerationOutputSelection",
    "CONTENT_VARIANT_PLATFORM_VALUES",
    "ContentVariantPlatform",
    "QA_ASSESSMENT_RESULT_VALUES",
    "QAAssessmentResult",
    "RIGHTS_ASSESSMENT_RESULT_VALUES",
    "RightsAssessmentResult",
    "ContentVariant",
    "ContentVariantRevision",
    "QAAssessment",
    "RightsAssessment",
    "MetricSnapshotSource",
    "METRIC_SNAPSHOT_SOURCE_VALUES",
    "MetricCompleteness",
    "METRIC_COMPLETENESS_VALUES",
    "MetricIngestionStatus",
    "METRIC_INGESTION_STATUS_VALUES",
    "ExperimentStatus",
    "EXPERIMENT_STATUS_VALUES",
    "ExperimentResultStatus",
    "EXPERIMENT_RESULT_STATUS_VALUES",
    "ExperimentAnalysisDesign",
    "EXPERIMENT_ANALYSIS_DESIGN_VALUES",
    "DEFAULT_EXPERIMENT_ANALYSIS_METHOD",
    "DEFAULT_EXPERIMENT_ANALYSIS_VERSION",
    "RevenueEventType",
    "REVENUE_EVENT_TYPE_VALUES",
    "MetricSnapshot",
    "MetricsSnapshot",
    "Experiment",
    "ExperimentResult",
    "ExperimentResultMetricInput",
    "ExperimentResultInput",
    "ExperimentMetricInput",
    "MetricSnapshotInput",
    "RevenueEvent",
    "LearningProposalStatus",
    "LEARNING_PROPOSAL_STATUS_VALUES",
    "LearningProposal",
    "VERIFICATION_ARTIFACT_CLEANUP_STATUSES",
    "VERIFICATION_CLEANUP_ITEM_STATUSES",
    "VERIFICATION_CLEANUP_STATUSES",
    "VERIFICATION_PROVENANCE_SCHEMA_VERSION",
    "VERIFICATION_RUN_STATUSES",
    "VerificationArtifactProvenance",
    "VerificationCleanupItem",
    "VerificationCleanupRun",
    "VerificationRun",
]
