"""Database models for conversation memory management

ドメイン別モジュールに分割したモデルパッケージ。公開APIは従来どおり
``from src.memory.models import <Model>`` で全モデル名を提供する。
"""

from sqlalchemy.orm import configure_mappers

from .base import Base
from .conversations import (
    ConversationSession,
    ConversationParticipant,
    ConversationMessage,
    ConversationArchive,
    ConversationHistory,
)
from .agent_runs import (
    AgentRun,
    AgentRunEdge,
    AgentRunEvent,
    AgentRunToolCall,
)
from .users import (
    User,
    LongLivedApiToken,
    WebUILoginLog,
    AppConfigSetting,
    FileExplorerBookmark,
    GoogleCalendarConnection,
    Feedback,
)
from .spotify import (
    SpotifyActivityLog,
    SpotifySessionSummary,
)
from .projects import (
    Space,
    Project,
    ProjectContextPack,
    ContextMemory,
    ProjectMember,
    ProjectQaEntry,
    ProjectJoinRequest,
)
from .records import (
    RecordTable,
    RecordField,
    RecordRow,
    RecordView,
    RecordAttachment,
    RecordEvent,
)
from .tasks import (
    LocalTask,
    TaskEvent,
    TaskExecutionSession,
    Task,
    TaskAssignee,
    TaskComment,
    TaskAttachment,
    TaskReference,
    TaskActivity,
    TaskDependency,
    TaskRecurrenceRule,
    TaskOccurrence,
    TimeEntry,
    Tag,
    TaskTag,
)
from .notifications import (
    ProjectNotificationSetting,
    NotificationDelivery,
)
from .knowledge import (
    KnowledgeAiSuggestion,
    KnowledgeAttachment,
    KnowledgeEdge,
    KnowledgeField,
    KnowledgeFieldValue,
    KnowledgeImportItem,
    KnowledgeImportJob,
    KnowledgeNode,
    KnowledgeNodePlacement,
    KnowledgeNodeSupertag,
    KnowledgeRevision,
    KnowledgeSavedView,
    KnowledgeSearchIndex,
    KnowledgeSource,
    KnowledgeSourcePermission,
    KnowledgeDocument,
    KnowledgeChunk,
    KnowledgeLink,
    KnowledgeAnnotation,
    KnowledgeEditEvent,
    KnowledgeSupertag,
    KnowledgeSupertagField,
    KnowledgeWorkspace,
)
from .remote import (
    RemoteServerProfile,
)
from .free_team import (
    FreeTeamCandidateModel,
    FreeTeamCredentialProfile,
    FreeTeamQuotaPool,
    FreeTeamReservation,
)
from .yomi import YomiDictionaryEntry, YomiDictionarySync, YomiUnresolvedCandidate

configure_mappers()

__all__ = [
    "AgentRun",
    "AgentRunEdge",
    "AgentRunEvent",
    "AgentRunToolCall",
    "AppConfigSetting",
    "Base",
    "ContextMemory",
    "ConversationArchive",
    "ConversationHistory",
    "ConversationMessage",
    "ConversationParticipant",
    "ConversationSession",
    "Feedback",
    "FileExplorerBookmark",
    "FreeTeamCandidateModel",
    "FreeTeamCredentialProfile",
    "FreeTeamQuotaPool",
    "FreeTeamReservation",
    "GoogleCalendarConnection",
    "KnowledgeAnnotation",
    "KnowledgeAiSuggestion",
    "KnowledgeAttachment",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "KnowledgeEdge",
    "KnowledgeEditEvent",
    "KnowledgeField",
    "KnowledgeFieldValue",
    "KnowledgeImportItem",
    "KnowledgeImportJob",
    "KnowledgeLink",
    "KnowledgeNode",
    "KnowledgeNodePlacement",
    "KnowledgeNodeSupertag",
    "KnowledgeRevision",
    "KnowledgeSavedView",
    "KnowledgeSearchIndex",
    "KnowledgeSource",
    "KnowledgeSourcePermission",
    "KnowledgeSupertag",
    "KnowledgeSupertagField",
    "KnowledgeWorkspace",
    "LocalTask",
    "LongLivedApiToken",
    "NotificationDelivery",
    "Project",
    "ProjectContextPack",
    "ProjectJoinRequest",
    "ProjectMember",
    "ProjectNotificationSetting",
    "ProjectQaEntry",
    "RecordAttachment",
    "RecordEvent",
    "RecordField",
    "RecordRow",
    "RecordTable",
    "RecordView",
    "RemoteServerProfile",
    "Space",
    "SpotifyActivityLog",
    "SpotifySessionSummary",
    "Tag",
    "Task",
    "TaskActivity",
    "TaskAssignee",
    "TaskAttachment",
    "TaskReference",
    "TaskComment",
    "TaskDependency",
    "TaskEvent",
    "TaskExecutionSession",
    "TaskOccurrence",
    "TaskRecurrenceRule",
    "TaskTag",
    "TimeEntry",
    "User",
    "WebUILoginLog",
    "YomiDictionaryEntry",
    "YomiDictionarySync",
    "YomiUnresolvedCandidate",
]
